version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 40s
      interval: 40s
      retries: 3
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
  car_sharing_app:
    container_name: car_sharing_app
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "$HIBERNATE_DDL_AUTO",
        "spring.jpa.show-sql" : "$SHOW_SQL",
        "springdoc.swagger-ui.disable-swagger-default-url" : "$DISABLE_SWAGGER_DEFAULT_URL",
        "springdoc.swagger-ui.path" : "$SWAGGER_PATH",
        "jwt.secret" : "$JWT_SECRET",
        "jwt.expiration" : "$JWT_EXPIRATION",
        "url.success" : "http://localhost:8080/api/payments/success",
        "url.cancel" : "http://localhost:8080/api/payments/cancel",
        "telegram.bot.token" : "$BOT_TOKEN",
        "telegram.chat.id" : "$CHAT_ID",
        "stripe.api.secret.key" : "$STRIPE_API_KEY"
      }'
